### PR TITLE
Use 2017 Build Tools

### PR DESCRIPTION
**Pull request by felixrieseberg**
This PR is a fairly big change - moving from the 2015 Build Tools to the 2017 Build Tools. New installer, new log files, new tailer.

### CODE REVIEW

**Comment by felixrieseberg** [comment]
@kittaakos Alright! I think this is pretty good now and certainly works on a freshly installed machine. I also updated the output a bit - the spinner is gone and replaced with the last few lines we've seen from the log files, which I hope improves the trust in this tool quite a bit.

It's currently publish as `2.1.5` under the `beta` tag. I'd love to hear if it works for you!

wbt

**Comment by felixrieseberg** [comment]
After a closer look, I'm afraid that tons of modules still don't build with 2017. I'll be backporting some changes and allow this thing to install both 2017 _and_ 2015.

**Comment by kittaakos** [comment]
> I'd love to hear if it works for you!

Sure, I am more than happy to check our build against your latest changes.

I am absolutely not a Windows power user, so could you please clarify a bit on the 1.x and the 2.x releases? Thank you!

Once I have tried out the new version I get back to you.

**Comment by felixrieseberg** [comment]
My initial thought was that the `1.x` branch would continue to use 2015 Build Tools while the `2.x` branch would go with the 2017 tools.

After a bit of research I'm convinced that `windows-build-tools` should continue to use the 2015 build tools by default. So, version 2.0 has only one hard breaking change, which is the new output format (that shows you the actual installer status).

**Comment by felixrieseberg** [comment]
I'm going to release the 2.x branch to `latest`. Here's to hoping that everything will be okay 🤞

**Comment by kittaakos** [comment]
👍 `windows-build-tools@2.2.1` works perfectly with our setup. Thank you!

**Comment by joaocgreis** [comment]
@felixrieseberg above you mention that some modules don't build with VS2017. I tried the modules listed in the README, and I get the same results with VS2015 and VS2017. Can you give details about the issues that you found, what modules don't build? Node should completely support VS2017, so if some modules are having issues I'd like to take a closer look. Thanks!

**Pull request merged**
